version: "3"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
  bot:
    depends_on:
      - mongodb
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./config/config.yml:/tmp/bot/config.yml
    env_file: ./.env
    stdin_open: true
    tty: true

volumes:
  db: